name: flutter_show
description: FlutterShow is an easy-to-use framework built in Flutter for crafting engaging and interactive presentations
publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  custom_mouse_cursor: ^1.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_macos_webview: ^0.0.6
  flutter_shaders: ^0.1.2
  flutter_svg: ^2.0.7
  flutter_widget_from_html_core: ^0.14.7
  fluttershow_base: ^1.1.1
  fluttershow_keynote: ^1.1.0
  fwfh_webview: ^0.14.2
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  intl_utils: ^2.8.1
  rive: ^0.12.3
  scratcher: ^2.3.0

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  generate: true

  assets:
    - assets/fonts/
    - assets/images/custom/
    - assets/images/shared/
    - assets/images/introduction/
    - assets/images/title_slide/
    - assets/images/website_review/
    - assets/images/embedding_process/
    - assets/images/js_interop/
    - assets/rive/

  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/GraphikSemibold.otf
          weight: 600
        - asset: assets/fonts/GraphikMedium.otf
          weight: 500
        - asset: assets/fonts/GraphikRegular.otf
          weight: 400

  shaders:
    - shaders/glitch.frag

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: assets/l10n
  ouput_dir: lib/generated

flutter_gen:
  output: lib/generated
  line_length: 80
  integrations:
    flutter_svg: true
